#flutter_gen配置文件

targets:
  $default:
    builders:
      flutter_gen:
        options: 
          output: lib/build_gen/ # Optional (default: lib/gen/)
          line_length: 180 # Optional (default: 80)